name: jumpnrun
version: '${project.version}'
main: org.gian.jumpnrun.Jumpnrun
api-version: '1.20'
commands:
  jumpnrun:
    description: "Teleport to the Jump and Run Map"
    usage: "/jumpnrun [easy|medium|hard]"